import type {
  CaseDefinition,
  KnowledgeRelation,
  PersonProfile,
  SourceRef,
} from '@/src/types/content';

export const sources: SourceRef[] = [
  {
    id: 'neea-312-outline',
    title: '全国硕士研究生招生考试心理学专业基础考试大纲',
    url: 'https://yankao.neea.edu.cn/xhtml1/category/1509/6235-1.htm',
    kind: 'official_outline',
    authority: 'A',
  },
  {
    id: 'apa-dictionary',
    title: 'APA Dictionary of Psychology',
    url: 'https://dictionary.apa.org/',
    kind: 'professional_association',
    authority: 'A',
  },
  {
    id: 'openstax-psychology',
    title: 'OpenStax Psychology 2e',
    url: 'https://openstax.org/details/books/psychology-2e',
    kind: 'reference',
    authority: 'B',
  },
  {
    id: 'psychclassics-york',
    title: 'Classics in the History of Psychology',
    url: 'https://psychclassics.yorku.ca/',
    kind: 'university',
    authority: 'A',
  },
  {
    id: 'bandura-bobo-1961',
    title: 'Transmission of aggression through imitation of aggressive models',
    url: 'https://doi.org/10.1037/h0045925',
    kind: 'original_research',
    authority: 'A',
  },
  {
    id: 'bandura-self-efficacy-1977',
    title: 'Self-efficacy: Toward a unifying theory of behavioral change',
    url: 'https://doi.org/10.1037/0033-295X.84.2.191',
    kind: 'original_research',
    authority: 'A',
  },
  {
    id: 'festinger-carlsmith-1959',
    title: 'Cognitive consequences of forced compliance',
    url: 'https://pubmed.ncbi.nlm.nih.gov/13640824/',
    kind: 'original_research',
    authority: 'A',
  },
  {
    id: 'festinger-social-comparison-1954',
    title: 'A Theory of Social Comparison Processes',
    url: 'https://journals.sagepub.com/doi/10.1177/001872675400700202',
    kind: 'original_research',
    authority: 'A',
  },
];

export const people: PersonProfile[] = [
  {
    id: 'hermann-ebbinghaus',
    canonicalNameZh: '赫尔曼·艾宾浩斯',
    canonicalNameEn: 'Hermann Ebbinghaus',
    aliases: ['艾宾浩斯', 'H. Ebbinghaus'],
    identity: '德国心理学家、实验记忆研究先驱',
    identityEn: 'German psychologist and pioneer of experimental memory research',
    lifetime: '1850–1909',
    tier: 'core',
    subjects: ['general', 'experiment'],
    epithet: '记忆回廊的测绘者',
    epithetEn: 'Cartographer of the Memory Arcade',
    summary: '以无意义音节、节省法和保持间隔研究记忆与遗忘。',
    summaryEn: 'Studied memory and forgetting with nonsense syllables, the savings method, and retention intervals.',
    motifs: ['记忆丝带', '重学计时器', '无意义音节'],
    accent: '#a78bfa',
    portraitIndex: 0,
    verified: true,
  },
  {
    id: 'jean-piaget',
    canonicalNameZh: '让·皮亚杰',
    canonicalNameEn: 'Jean Piaget',
    aliases: ['皮亚杰', 'J. Piaget'],
    identity: '瑞士心理学家、发生认识论创立者',
    identityEn: 'Swiss psychologist and founder of genetic epistemology',
    lifetime: '1896–1980',
    tier: 'core',
    subjects: ['development', 'education'],
    epithet: '认知阶梯的构筑师',
    epithetEn: 'Architect of the Cognitive Stairway',
    summary: '提出认知发展阶段，并以图式、同化、顺应和平衡解释发展。',
    summaryEn: 'Proposed stages of cognitive development and explained change through schemas, assimilation, accommodation, and equilibration.',
    motifs: ['四阶晶柱', '螺旋贝壳', '守恒之杯'],
    accent: '#34d399',
    portraitIndex: 1,
    verified: true,
  },
  {
    id: 'albert-bandura',
    canonicalNameZh: '阿尔伯特·班杜拉',
    canonicalNameEn: 'Albert Bandura',
    aliases: ['班杜拉', 'A. Bandura'],
    identity: '加拿大裔美国心理学家、社会认知理论代表',
    identityEn: 'Canadian-American psychologist and leading social cognitive theorist',
    lifetime: '1925–2021',
    tier: 'core',
    subjects: ['general', 'social', 'education', 'experiment'],
    epithet: '镜像剧场的观察者',
    epithetEn: 'Observer of the Mirror Theatre',
    summary: '研究观察学习、榜样作用、自我效能与三元交互决定。',
    summaryEn: 'Studied observational learning, modeling, self-efficacy, and triadic reciprocal determinism.',
    motifs: ['观察镜', '微型剧场', '效能光环'],
    accent: '#fbbf24',
    portraitIndex: 2,
    verified: true,
  },
  {
    id: 'leon-festinger',
    canonicalNameZh: '利昂·费斯廷格',
    canonicalNameEn: 'Leon Festinger',
    aliases: ['费斯廷格', 'L. Festinger'],
    identity: '美国社会心理学家',
    identityEn: 'American social psychologist',
    lifetime: '1919–1989',
    tier: 'core',
    subjects: ['social', 'experiment'],
    epithet: '失调罗盘的校准者',
    epithetEn: 'Calibrator of the Dissonance Compass',
    summary: '提出认知失调理论和社会比较理论，并与卡尔史密斯检验强迫服从。',
    summaryEn: 'Developed cognitive dissonance and social comparison theories, and tested forced compliance with James Carlsmith.',
    motifs: ['双向罗盘', '平衡线', '比较尺度'],
    accent: '#fb7185',
    portraitIndex: 3,
    verified: true,
  },
  {
    id: 'gustav-fechner',
    canonicalNameZh: '古斯塔夫·费希纳',
    canonicalNameEn: 'Gustav Theodor Fechner',
    aliases: ['费希纳', 'G. T. Fechner'],
    identity: '德国心理物理学家、哲学家',
    identityEn: 'German psychophysicist and philosopher',
    lifetime: '1801–1887',
    tier: 'core',
    subjects: ['general', 'experiment'],
    epithet: '感觉刻度的点灯人',
    epithetEn: 'Lamplighter of the Sensory Scale',
    summary: '奠定心理物理学，并在韦伯研究基础上推导对数关系。',
    summaryEn: 'Helped found psychophysics and derived a logarithmic relation from Weber’s findings.',
    motifs: ['双烛', '砝码', '对数螺旋'],
    accent: '#f59e0b',
    portraitIndex: 4,
    verified: true,
  },
  {
    id: 'charles-spearman',
    canonicalNameZh: '查尔斯·斯皮尔曼',
    canonicalNameEn: 'Charles Spearman',
    aliases: ['斯皮尔曼', 'C. Spearman'],
    identity: '英国心理学家、心理统计学家',
    identityEn: 'British psychologist and psychometrician',
    lifetime: '1863–1945',
    tier: 'core',
    subjects: ['general', 'statistics', 'measurement'],
    epithet: '群星秩序的析光者',
    epithetEn: 'Prism-Keeper of the Constellation',
    summary: '提出智力二因素理论与等级相关，并独立参与信度校正公式的建立。',
    summaryEn: 'Developed the two-factor theory of intelligence and rank correlation, and independently contributed to the reliability correction formula.',
    motifs: ['秩序星牌', 'g因素棱镜', '信度晶球'],
    accent: '#38bdf8',
    portraitIndex: 5,
    verified: true,
  },
];

export const relations: KnowledgeRelation[] = [
  {
    id: 'rel-ebbinghaus-savings',
    personId: 'hermann-ebbinghaus',
    knowledgePointId: 'memory.ebbinghaus.savings-method',
    subjects: ['general', 'experiment'],
    relationType: 'experimented',
    examRole: 'primary',
    claim: '艾宾浩斯以重学所节省的时间或次数量化保持。',
    claimEn: 'Ebbinghaus quantified retention by the time or trials saved during relearning.',
    sourceIds: ['psychclassics-york', 'apa-dictionary'],
    confusionWith: ['自由回忆法', '再认法'],
  },
  {
    id: 'rel-ebbinghaus-forgetting',
    personId: 'hermann-ebbinghaus',
    knowledgePointId: 'memory.ebbinghaus.nonsense-syllables-forgetting',
    subjects: ['general', 'experiment'],
    relationType: 'experimented',
    examRole: 'primary',
    claim: '艾宾浩斯用无意义音节与保持间隔研究遗忘进程。',
    claimEn: 'Ebbinghaus studied forgetting with nonsense syllables and varied retention intervals.',
    sourceIds: ['psychclassics-york'],
  },
  {
    id: 'rel-piaget-stages',
    personId: 'jean-piaget',
    knowledgePointId: 'development.piaget.four-stages',
    subjects: ['development'],
    relationType: 'proposed',
    examRole: 'primary',
    claim: '皮亚杰提出感知运动、前运算、具体运算和形式运算四阶段。',
    claimEn: 'Piaget proposed the sensorimotor, preoperational, concrete operational, and formal operational stages.',
    sourceIds: ['openstax-psychology'],
  },
  {
    id: 'rel-piaget-assimilation',
    personId: 'jean-piaget',
    knowledgePointId: 'development.piaget.assimilation-accommodation',
    subjects: ['development', 'education'],
    relationType: 'proposed',
    examRole: 'primary',
    claim: '同化用原有图式解释经验，顺应则修改图式。',
    claimEn: 'Assimilation interprets experience through existing schemas; accommodation modifies those schemas.',
    sourceIds: ['openstax-psychology'],
  },
  {
    id: 'rel-piaget-conservation',
    personId: 'jean-piaget',
    knowledgePointId: 'development.piaget.conservation-centration',
    subjects: ['development', 'experiment'],
    relationType: 'experimented',
    examRole: 'primary',
    claim: '守恒任务揭示前运算阶段的集中化与具体运算阶段的去中心化。',
    claimEn: 'Conservation tasks contrast preoperational centration with concrete-operational decentration.',
    sourceIds: ['openstax-psychology'],
  },
  {
    id: 'rel-bandura-modeling',
    personId: 'albert-bandura',
    knowledgePointId: 'education.bandura.modeling-processes',
    subjects: ['education', 'general'],
    relationType: 'proposed',
    examRole: 'primary',
    claim: '观察学习包括注意、保持、动作再现和动机。',
    claimEn: 'Observational learning involves attention, retention, motor reproduction, and motivation.',
    sourceIds: ['openstax-psychology'],
  },
  {
    id: 'rel-bandura-bobo',
    personId: 'albert-bandura',
    knowledgePointId: 'experiment.bandura.bobo-doll',
    subjects: ['experiment', 'education', 'social'],
    relationType: 'co_tested',
    examRole: 'co_tested',
    claim: '波波玩偶研究由 Albert Bandura、Dorothea Ross 与 Sheila Ross 共同完成。',
    claimEn: 'The Bobo doll study was conducted by Albert Bandura, Dorothea Ross, and Sheila Ross.',
    sourceIds: ['bandura-bobo-1961'],
    confusionWith: ['班杜拉单独署名'],
  },
  {
    id: 'rel-bandura-efficacy',
    personId: 'albert-bandura',
    knowledgePointId: 'education.bandura.self-efficacy',
    subjects: ['education', 'general'],
    relationType: 'proposed',
    examRole: 'primary',
    claim: '自我效能是个体对完成特定行为能力的判断。',
    claimEn: 'Self-efficacy is one’s judgment of the ability to perform a specific action.',
    sourceIds: ['bandura-self-efficacy-1977', 'apa-dictionary'],
  },
  {
    id: 'rel-festinger-dissonance',
    personId: 'leon-festinger',
    knowledgePointId: 'social.festinger.cognitive-dissonance',
    subjects: ['social'],
    relationType: 'proposed',
    examRole: 'primary',
    claim: '费斯廷格提出认知失调理论。',
    claimEn: 'Festinger proposed cognitive dissonance theory.',
    sourceIds: ['apa-dictionary'],
  },
  {
    id: 'rel-festinger-compliance',
    personId: 'leon-festinger',
    knowledgePointId: 'social.festinger.forced-compliance',
    subjects: ['social', 'experiment'],
    relationType: 'co_tested',
    examRole: 'co_tested',
    claim: '强迫服从实验由费斯廷格与 James Carlsmith 共同完成。',
    claimEn: 'The forced-compliance experiment was conducted by Leon Festinger and James Carlsmith.',
    sourceIds: ['festinger-carlsmith-1959'],
    confusionWith: ['费斯廷格单独署名'],
  },
  {
    id: 'rel-festinger-comparison',
    personId: 'leon-festinger',
    knowledgePointId: 'social.festinger.social-comparison',
    subjects: ['social'],
    relationType: 'proposed',
    examRole: 'primary',
    claim: '费斯廷格以评价意见与能力的动机解释社会比较。',
    claimEn: 'Festinger explained social comparison through the drive to evaluate opinions and abilities.',
    sourceIds: ['festinger-social-comparison-1954'],
  },
  {
    id: 'rel-fechner-law',
    personId: 'gustav-fechner',
    knowledgePointId: 'sensation.fechner.weber-fechner-law',
    subjects: ['general', 'experiment'],
    relationType: 'developed',
    examRole: 'primary',
    claim: '费希纳在韦伯关系基础上推导感觉量与刺激量的对数关系。',
    claimEn: 'Fechner derived a logarithmic relation between sensation and stimulus magnitude from Weber’s relation.',
    sourceIds: ['psychclassics-york'],
    confusionWith: ['韦伯定律的提出者'],
  },
  {
    id: 'rel-fechner-methods',
    personId: 'gustav-fechner',
    knowledgePointId: 'experiment.fechner.classical-psychophysical-methods',
    subjects: ['experiment'],
    relationType: 'developed',
    examRole: 'primary',
    claim: '经典心理物理法包括极限法、恒定刺激法与调整法。',
    claimEn: 'Classical psychophysical methods include limits, constant stimuli, and adjustment.',
    sourceIds: ['psychclassics-york'],
  },
  {
    id: 'rel-spearman-intelligence',
    personId: 'charles-spearman',
    knowledgePointId: 'intelligence.spearman.g-s-factors',
    subjects: ['general', 'measurement'],
    relationType: 'proposed',
    examRole: 'primary',
    claim: '斯皮尔曼用共同的 g 因素和任务特有的 s 因素解释智力表现。',
    claimEn: 'Spearman explained intelligence with a common g factor and task-specific s factors.',
    sourceIds: ['apa-dictionary'],
  },
  {
    id: 'rel-spearman-rank',
    personId: 'charles-spearman',
    knowledgePointId: 'statistics.spearman.rank-correlation',
    subjects: ['statistics'],
    relationType: 'statistical_method_created',
    examRole: 'primary',
    claim: '斯皮尔曼等级相关衡量两个等级变量的单调关联。',
    claimEn: 'Spearman rank correlation measures monotonic association between two ranked variables.',
    sourceIds: ['apa-dictionary'],
  },
  {
    id: 'rel-spearman-brown',
    personId: 'charles-spearman',
    knowledgePointId: 'measurement.spearman-brown-prophecy',
    subjects: ['measurement', 'statistics'],
    relationType: 'co_tested',
    examRole: 'co_tested',
    claim: 'Spearman 与 William Brown 在 1910 年分别发表相关推导，并非共同署名。',
    claimEn: 'Spearman and William Brown published related derivations separately in 1910; they did not coauthor one paper.',
    sourceIds: ['apa-dictionary'],
    confusionWith: ['Spearman 与 Brown 合写一篇论文'],
  },
];

export const firstCase: CaseDefinition = {
  id: 'misfiled-scholars',
  title: '错位的学者档案',
  titleEn: 'The Misfiled Scholars',
  subtitle: '第一案 · 七域交叉强化',
  subtitleEn: 'Case One · Seven-Domain Retrieval',
  estimatedMinutes: 18,
  nodeIds: Array.from({ length: 16 }, (_, index) => `node-${String(index + 1).padStart(2, '0')}`),
  castIds: people.map((person) => person.id),
  synopsis:
    '心境档案馆的理论页被一只“张冠李戴”误区精灵重新装订。循着六位学者留下的证据，把人物、理论、实验与方法放回正确位置。',
  synopsisEn:
    'A misconception spirit has rebound the Mind Archive’s theory pages under the wrong names. Follow six scholars’ evidence and return each person, theory, experiment, and method to its proper place.',
};
